name: Release CI

on:
  push:
    tags:
      - "v*"

jobs:
  build-winform:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore "./"

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish "./"

      - name: Archive Release
        run: 7z a -tzip QuadToSpineJson_Windows.zip publish/

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          includeInvalidCommits: true

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "QuadToSpineJson_Windows.zip"
          allowUpdates: true
          body: |
            ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
